#!/usr/bin/python3

import sys
import json
import boto3

context = json.loads(sys.stdin.read())['source']

region     = context['region_name']
access_key = context['access_key']
secret_key = context['secret_key']
queue_url  = context['queue_url']

client = boto3.client('sqs', region_name=region, aws_access_key_id=access_key, aws_secret_access_key=secret_key)

response = client.receive_message(QueueUrl=queue_url, MaxNumberOfMessages=1, VisibilityTimeout=0)

if 'Messages' in response:
    messages = response['Messages']
    print(json.dumps(list(map(lambda x: {'ref': x['MessageId']}, messages))))
else:
    print(json.dumps([]))

